name: Sync with doomemacs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "nonexist@nonexist.com" && git config --global user.name "nonexist"
      - run: git clone https://github.com/doomemacs/doomemacs /tmp/doomemacs
      - run: cp -vf /tmp/doomemacs/bin/org-tangle .
      - run: cp -vf /tmp/doomemacs/bin/org-capture .
      - run: sed -i -e "/'org-babel-tangle-collect-blocks/,+1d" ./org-tangle || true
      - run: git add .
      - run: git commit -m "Periodically sync with doomemacs commit $(cd /tmp/doomemacs/ && git log --format=%H -1)" || true
      - run: git push 
